env.account_moniker="s3sns-dev"
env.aws_account="326963205453"
env.aws_region="us-east-1"
env.provisioner_role="s3sns-slave-role"
env.tf_path="/var/lib/jenkins/workspace/tfs3sns/"
env.tf_vars="egress-bucket.tfvars"
env.git_user="prasadambasaveswar"
env.git_url="https://github.com/prasadambasaveswar/tfs3sns.git"
